AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Verdict API - AWS Lambda & API Gateway"

Parameters:
  StageName:
    Type: String
    AllowedValues:
      - dev
      - prod
  FrontendUrl:
    Type: String

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  VerdictApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: !Sub "'${FrontendUrl}'"

  VerdictFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: .
      Handler: cmd
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CreatePoll:
          Type: Api 
          Properties:
            Path: /poll
            Method: POST
            RestApiId: !Ref VerdictApi
        GetPoll:
          Type: Api
          Properties:
            Path: /poll/{pollId}
            Method: GET
            RestApiId: !Ref VerdictApi

Outputs:
  VerdictAPI:
    Description: "API Gateway endpoint for Verdict API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
