AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Verdict API - AWS Lambda & API Gateway"

Parameters:
  StageName:
    Type: String
    AllowedValues:
      - dev
      - prod
  FrontendUrl:
    Type: String

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  VerdictApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: !Sub "'${FrontendUrl}'"

  VerdictFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: .
      Handler: cmd
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Environment:
        Variables:
          FRONTEND_URL: !Ref FrontendUrl
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:Query
            Resource:
              - !GetAtt BallotsTable.Arn
              - !GetAtt PollsTable.Arn
      Events:
        CreatePoll:
          Type: Api 
          Properties:
            Path: /poll
            Method: POST
            RestApiId: !Ref VerdictApi
        GetPoll:
          Type: Api
          Properties:
            Path: /poll/{pollId}
            Method: GET
            RestApiId: !Ref VerdictApi
        CastBallot:
          Type: Api
          Properties:
            Path: /ballot
            Method: POST
            RestApiId: !Ref VerdictApi
        GetResult:
          Type: Api
          Properties:
            Path: /result/{pollId}
            Method: GET
            RestApiId: !Ref VerdictApi

  BallotsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Ballots
      AttributeDefinitions:
        - AttributeName: PollID
          AttributeType: S
        - AttributeName: UserID
          AttributeType: S
      KeySchema:
        - AttributeName: PollID
          KeyType: HASH
        - AttributeName: UserID
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  PollsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Polls
      AttributeDefinitions:
        - AttributeName: PollID
          AttributeType: S
      KeySchema:
        - AttributeName: PollID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST


Outputs:
  VerdictAPI:
    Description: "API Gateway endpoint for Verdict API"
    Value: !Sub "https://${VerdictApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
